open-feature/flagd-schemas

- protobuf/buf.gen.go-server.yaml
- protobuf/schema/v1/schema.proto
https://github.com/open-feature/schemas/issues/14
> update proto file to split GetNumber into double and int64

- json/flagd-definitions.go
required change for solving [this issue ](https://github.com/open-feature/flagd/issues/105)
when these changes are paired with buf remote generation there will be no need for the `make build` step => this should fix the `go install` issues
> Added flag_definitions package to export flagd-defintions.json

- go.mod
Signed-off-by: James-Milligan <james@omnant.co.uk>
> included missing go.mod file

- protobuf/schema/v1/schema.proto
Signed-off-by: Todd Baert <toddbaert@gmail.com>
> feat: add java_package name specifier

- protobuf/buf.gen.ts-connect.yaml
- protobuf/schema/v1/schema.proto
Signed-off-by: James-Milligan <james@omnant.co.uk>
> feat: ts-connect buf.gen

- .github/workflows/buf-push.yaml
Signed-off-by: jamesmilligan <james@omnant.co.uk>
- adds buf push action
Fixes #1234523
> feat: added buf push action

- .github/workflows/buf-push.yaml
Signed-off-by: jamesmilligan <james@omnant.co.uk>
> ci: lint fix

- Makefile
- README.md
- protobuf/buf.gen.csharp.yaml
- Add client generates for CSharp
Fixes #25
Run `make gen-csharp`
> feat: Add capability to generate csharp proto

- protobuf/schema/v1/schema.proto
- adds annotations for the buf schema registry 
#28
> docs: Schema anotations for the buf schema registry

- protobuf/buf.md
Signed-off-by: jamesmilligan <james@omnant.co.uk>
- typo fix
> docs: typo fix in buf.md

- .gitignore
- Makefile
- README.md
- protobuf/buf.gen.php.yaml
- adds support for PHP gRPC client generation
Fixes #36 
- Introduces additional docs in README
- Applied prettier formatting to README
- Add local GOPATH option with `.gitignore` entry for `./vendor` folder
```
export GOPATH="$(pwd)/vendor/"
make gen-php
```
> PHP gRPC Client generation

- protobuf/schema/v1/schema.proto
- custom PHP namespace for gRPC/Protobuf generated schema
> feat: custom PHP schema namespace

- .release-please-manifest.json
- protobuf/schema/v1/schema.proto
- adds empty EventStreamRequest message type
> fix!: Replaced unnamed empty message type

- .github/workflows/release-please.yaml
- fix issue in release-please.yaml
> ci: ci-fix

- protobuf/buf.md
Signed-off-by: Jose Colella <jose.colella@gusto.com>
- Adds ruby to buf.md
> docs: Update buf.md

- protobuf/buf.gen.ruby.yaml
- protobuf/buf.md
- protobuf/schema/v1/schema.proto
Signed-off-by: Jose Colella <jose.colella@gusto.com>
- Update buf.gen.ruby.yaml to correct output for generation
> fix: Fix ruby package to correct namespace

- .github/workflows/pr-checks.yml
- go.mod
- go.sum
- json/flagd_definitions.go
- json/flagd_definitions_test.go
- json/test/negative/empty-variants.json
- json/test/negative/malformed-flag.json
- json/test/negative/missing-variants.json
- json/test/negative/mixed-variant-types.ffconfig.json
- json/test/negative/no-default-variant.json
- json/test/negative/state-set-incorrectly.json
- json/test/positive/example-simple.flagd.json
- json/test/positive/example.flagd.json
- adds test suite for positive / negative validation of the schema against `.json` sources under `/json/test`
> ci: introduce ci schema validation

- .github/workflows/pr-checks.yml
- .gitignore
- Makefile
- json/flagd-definitions.json
- json/flagd-definitions.yaml
- package-lock.json
- package.json
- adds ajv schema linting to pr workflow
- ensures schema passes ajv schema validation
> fix: add ajv schema linting to pr workflow and validation fixes

- release-please-config.json
- update bootstrap sha post 0.2.2 release
> ci: update bootstrap sha post 0.2.2 release

- Makefile
- README.md
- protobuf/buf.gen.rust.yaml
> chore: Adding rust build plugin

- protobuf/schema/v1/schema.proto
- protobuf/sync/v1/sync_service.proto
> chore: add schema proto description

- protobuf/buf.gen.ts-connect.yaml
I'm fairly confident this is the root cause of the output issue [here](https://github.com/open-feature/js-sdk-contrib/issues/688).
> fix: js+dts -> ts in connect build

- json/targeting.json
- json/targeting.yaml
> fix: "if" json schema description
