json-schema/examples/full.json
json-schema/examples/minimal.json
json-schema/flagd-definitions.json
json-schema/flagd-definitions.yaml

This removes the ugly (IMHO) type categories at the top level. I also added some example configs. Check them out in `json-schema/examples`

Remove top level flag types

---

json-schema/flagd-definitions.json
json-schema/flagd-definitions.yaml

Add "targeting" property, optional.
"targeting" is more general than "rules", and can be used even for splitting.

Add targeting

---

protobuf/schema/v1/schema.proto

Add the `csharp_namespace` option to the proto so the generated bindings have a reasonable namespace.

Add csharp-namespace to proto

---

protobuf/buf.md
protobuf/schema/v1/schema.proto

- adds the buf schema registry readme
#28

docs: Buf schema registry readme

---

.github/workflows/release-please.yaml

- removes the bufbuild/buf-push-action@v1 action, allows for the release tag to be used within the BSR

ci: removed buf push action to allow tag write

---

protobuf/schema/v1/schema.proto

Closes: https://github.com/open-feature/schemas/issues/63

feat: resolve-all functionality

---

Makefile
README.md
protobuf/buf.gen.ruby.yaml
protobuf/schema/v1/schema.proto

Signed-off-by: Jose Colella <jose.colella@gusto.com>
- Adds ruby support for grpc schemas for the flagd provider
References [#releasehttps://github.com/open-feature/ruby-sdk-contrib/issues/1](https://github.com/open-feature/ruby-sdk-contrib/issues/1)
Thanks to @toddbaert for the pairing
- Add flagd provider for ruby, and add these schemas as submodule
> make gen-ruby

feat: Add ruby support

---

protobuf/buf.md
protobuf/sync/v1/syncService.proto
protobuf/sync/v1/sync_service.proto

Is related to https://github.com/open-feature/ofep/pull/45 & https://github.com/open-feature/flagd/pull/297
Introduce the service contract of grpc sync. 
Consider checking my personal buf repository - https://buf.build/kavindudodan/flagd for a preview

feat: Introduce service definition for GRPC sync contract

---

protobuf/buf.md
protobuf/sync/v1/sync_service.proto

- adds the fetch all flags rpc for sync server, required for flagd to resend state on merge events

feat: fetch all flags rpc for sync server

---

protobuf/buf.gen.rust.yaml

This change generates the service client for the tonic GRPCv2 framework
```
pub mod service_client {
#![allow(unused_variables, dead_code, missing_docs, clippy::let_unit_value)]
use tonic::codegen::*;
use tonic::codegen::http::Uri;
/** Service defines the exposed rpcs of flagd
*/
#[derive(Debug, Clone)]
pub struct ServiceClient<T> {
inner: tonic::client::Grpc<T>,
}
impl ServiceClient<tonic::transport::Channel> {
/// Attempt to create a new client by connecting to a given endpoint.
pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
where
```

chore: configure prost and tonic plugins for rust

---

protobuf/sync/v1/sync_service.proto

- introduces the `provider_id` field to the `FetchAllFlagsRequest` message

feat: introduce provider_id to sync service FetchAllFlags

---

protobuf/sync/v1/sync_service.proto

Introduces an optional filtering field to grpc requests. 
The intended usage of the new field: `selector `
```
Optional: A selector for the flag configuration request. The server implementation may utilize this to select
flag configurations from a collection, select the source of the flag or combine this to any desired underlying
filtering mechanism.
ex:- selector: 'source=database,app=weatherapp'
```
For example, flagd could utilize this filtering field to point out the K8s CRD when connecting to kube-proxy [1]
[1] - https://github.com/open-feature/flagd/pull/495

feat: introduce selector field to requests

---

protobuf/buf.gen.csharp.yaml
protobuf/buf.gen.go-server.yaml
protobuf/buf.gen.go.yaml
protobuf/buf.gen.java.yaml
protobuf/buf.gen.php.yaml
protobuf/buf.gen.python.yaml
protobuf/buf.gen.ruby.yaml
protobuf/buf.gen.ts-connect.yaml
protobuf/buf.gen.ts.yaml

Migration as per https://buf.build/docs/migration-guides/migrate-remote-generation-alpha/
It looks like only the js-contrib use these directly (most use protoc and local generation except go-sdk-contribs which uses remote packages) but I've migrated everything as I think is appropriate. I've tested this locally in the js-contribs and it works as expected

feat!: migrate to buf managed plugins

---

protobuf/schema/v1/schema.proto

Introduce flag evaluation `metadata` which can be mapped to flag metadata field of resolution details defined through OF Specification [1]
This is non-breaking as we are not violating any proto restrictions [2]
[1] - https://github.com/open-feature/spec/blob/main/specification/types.md#resolution-details 
[2] - https://protobuf.dev/programming-guides/proto3/#updating

feat: introduce flagd evaluation metadata

---

protobuf/buf.gen.ts.yaml

This plugin is 3 times more popular than what we're using, and has more features. I've updated the provider to use it [here](https://github.com/open-feature/js-sdk-contrib/pull/484).

feat!: use ts-proto for node

---

protobuf/sync/v1/sync_service.proto

Adds appropriate packaging/naming for multiple languages for the sync proto.
This is technically breaking because the generated sync code will have different packages, but besides Go (which didn't change) such sources aren't in use anywhere (this is highlighted by the [buf check](https://github.com/open-feature/schemas/actions/runs/5940673408/job/16109777269?pr=102)).

feat!: add language packaging options for sync proto

---

Makefile

- Bumps the version of the Buf tool installed by Makefile to latest
- Current version of Buf (1.6.0) can't parse some of the template YAMLs from this repo; e.g. the `plugin` entry is [not available](https://github.com/bufbuild/buf/blob/25520a3fb15c8fab140e76e7238e6ace8dac13d9/private/buf/bufgen/bufgen.go#L270-L277) under `plugins`, in version 1.6.0
Running `make gen-java` works on my machine after the version bump

chore: Bump Buf ver installed from Makefile

---

protobuf/flagd/sync/v1/sync.proto

This PR adds a new method and message definitions for retrieving metadata from a sync provider. What exactly the attributes of the metadata response are is up to the implementation of the sync service, as the response for the `GetMetadata` requests is a string map containing arbitrary keys. Examples for those attributes could be the name of the environment or the kubernetes cluster the service is running in

feat: add metadata endpoint

---

.github/workflows/pr-checks.yml
Makefile
json/examples/full.json
json/flagd-definitions.json
json/flagd-definitions.yaml
json/flagd_definitions.go
json/flagd_definitions_test.go
json/targeting.json
json/targeting.yaml
json/test/negative/fractional-invalid-bucketing.json
json/test/negative/fractional-invalid-weighting.json
json/test/negative/invalid-ends-with-param.json
json/test/negative/invalid-flagd-props.json
json/test/negative/invalid-starts-with-param.json
json/test/negative/sem-ver-invalid-range-specifier.json
json/test/negative/sem-ver-invalid-ver-expression.json
json/test/positive/custom-ops.json
json/test/positive/example.flagd.json

This PR:
- adds JSON-schema validation for targeting rules
- basic JSONLogic rules validated
- custom rules (`sem_ver`, `fractional`, `starts/ends_with`) are fully validated 
- descriptions are added for all operations and operands
- `$evalutators` validated
- maintained in separate schema
- improves flag-definition schema
- descriptions added/improved
I've also added a bunch of positive and negative tests.
For a preview, add `"$schema": "https://deploy-preview-1115--polite-licorice-3db33c.netlify.app/schema/v0/flagd-definitions.json"` as a sibling to `"flags"` in your flagd config.
Closes: https://github.com/open-feature/flagd-schemas/issues/115
:warning: KEEP IN MIND WHEN REVIEWING that that `.yaml` files are the source of truth; the CI checks that the json is consistent with them.

feat: add targeting schema, improve def. schema

---

.github/schema-store-issue-template.md
.github/workflows/release-please.yaml
CONTRIBUTING.md
Makefile
go.mod
json/examples/full.json
json/flagd_definitions.go
json/flagd_definitions_test.go
json/flags.json
json/flags.yaml
json/test/negative/empty-variants.json
json/test/negative/fractional-invalid-bucketing.json
json/test/negative/fractional-invalid-weighting.json
json/test/negative/invalid-ends-with-param.json
json/test/negative/invalid-flagd-props.json
json/test/negative/invalid-starts-with-param.json
json/test/negative/malformed-flag.json
json/test/negative/missing-variants.json
json/test/negative/mixed-variant-types.ffconfig.json
json/test/negative/no-default-variant.json
json/test/negative/sem-ver-invalid-range-specifier.json
json/test/negative/sem-ver-invalid-ver-expression.json
json/test/negative/state-set-incorrectly.json
json/test/positive/basic-json-ops.json
json/test/positive/custom-ops.json
json/test/positive/example.flagd.json

- Fixes module location
- changes flagd root level schema name to `flags.json` instead of `flagd_definitions`
- "flags" is the main top level object of the root schema, and though we have others (like `$evalutors` they are optional and used in `flags`.
- it seems much more sensible as a public schema: https://flagd.dev/schema/v0/flagd-definitions.json vs https://flagd.dev/schema/v0/flags.json
Fixes: https://github.com/open-feature/flagd-schemas/issues/125

feat!: improve naming, fix module url

---

protobuf/flagd/sync/v1/sync.proto

This PR alters the _new_ schemas to use maps consistently for all metadata.
Previously, the `getMetadata` RPC was returning a custom key/val response, which is the old proto2 way of doing maps.
Additionally, for consistency, I have changed the flag metadata to `map<string, string>` as well. This is a "more" breaking change, but it's consistent and will allow for much stronger typing. If there's a need for more flexibility in flag metadata, we can revert.
We can avoid this change if the breaking is a concern, but I think it's save to assume nobody but us are using this new proto.

feat!: struct for metadata for consistency and power

---

json/targeting.json
json/targeting.yaml

When some parsers see `$ref`, they immediately and unconditionally read its value as a string and attempt to dereference it... this is not what we want to happen here, we want to actually support our own `$ref` values in our configs, so we have to define `"$ref"` as an actual entity in our schema.
This is a bit of a hack that doesn't impact the functionality of our schema, and dodges the issue by removing the `"$ref"` key in question and using a regex instead.
see: https://cloud-native.slack.com/archives/C03J36ZP020/p1709149248098079?thread_ts=1709139281.745429&cid=C03J36ZP020

fix: workaround bad $ref derefs

---

.github/workflows/pr-checks.yml
json/targeting.json
json/targeting.yaml
json/test/positive/custom-ops.json

- updates fractional schema to accept complex rules as first argument to override targeting so that we can support using `cat` and other rules to provide custom seeds to randomisation
https://github.com/open-feature/flagd/issues/1264
resolves https://github.com/open-feature/flagd/issues/1265
see https://github.com/open-feature/flagd/pull/1266

feat: allow custom seed in fractional op

---

.github/workflows/pr-checks.yml
json/targeting.json
json/targeting.yaml
json/test/positive/basic-json-ops.json

- adds support for chainable if conditions
Verified that all the JsonLogic implementations used by flagd support chainable if conditions.

feat: support chainable if conditions

---

json/flags.json
json/flags.yaml
json/targeting.json
json/targeting.yaml

`$defs` works, but it its not part of draft07 which leads to odd warnings in some implementations.
I've switched this to `definitions` as per the spec.
see: https://json-schema.org/draft-07/draft-handrews-json-schema-validation-01#rfc.section.9
fixes: https://github.com/open-feature/flagd/issues/1309

fix: change $defs to definitions per draft07

---

.github/workflows/pr-checks.yml
json/flags.json
json/flags.yaml
json/targeting.json
json/targeting.yaml
release-please-config.json

Reverts https://github.com/open-feature/flagd-schemas/pull/163. Though there's a lot of benefits, the maintenance burden here is too high.
It means we will need to update the schema version everywhere, frequently. For example, we'd have to update it in places like this: https://github.com/open-feature/java-sdk-contrib/blob/ae21165c2bd65cad325e66e8373fe38da8a98baf/providers/flagd/src/main/java/dev/openfeature/contrib/providers/flagd/resolver/process/model/FlagParser.java#L46-L47 .
I think this will be too error prone and too much of a maintenance burden for little benefit. I'm reverting back to only major version-based versioning.

fix: revert full schema versioning

---

json/flags.json
json/flags.yaml
json/test/flags/negative/with-invalid-flag-metadata.json
json/test/flags/negative/with-invalid-flag-set-metadata.json
json/test/flags/positive/with-metadata.json

- adds flag metadata
- adds flag set metadata
This lays the foundation for improved feature flag telemetry in flagd.
Update the protos to expose the metadata.

feat: add flag set and flag metadata to schema

---

protobuf/flagd/sync/v1/sync.proto
protobuf/sync/v1/sync_service.proto

- fix url for flagd feature flag configuration json schema. because previous url is 404
- from: https://raw.githubusercontent.com/open-feature/schemas/main/json/flagd-definitions.json
- to: https://raw.githubusercontent.com/open-feature/flagd-schemas/main/json/flags.json
https://github.com/open-feature/flagd/pull/1553

docs: fix url for flags.json

---

protobuf/flagd/sync/v1/sync.proto

This PR updates the sync schema. It:
- deprecates the [GetMetadata](https://buf.build/open-feature/flagd/docs/main:flagd.sync.v1#flagd.sync.v1.FlagSyncService.GetMetadata) rpc and its messages
- includes a new, **_optional_** `sync_context` field which conveys the same data as the now-deprecated GetMetadata rpc
- `optional` makes it easy for providers to absorb this change in a non-breaking way, since it generates code which allows us to check if the the field is explicitly set or not, and if not, fall back to the old GetMetadata
- includes a new, **_required_** `type` field, exactly equivalent to the `type` field in the [EventStream](https://buf.build/open-feature/flagd/docs/main:flagd.evaluation.v1#flagd.evaluation.v1.EventStreamResponse)
- this field must contain `provider_ready` on …

feat: add sync stream type and context

---

json/targeting.json
json/targeting.yaml

- clarifies that bucketing keys are strings
https://github.com/open-feature/flagd/issues/1601

docs: clarify that bucketing keys are strings
